
package maintest;

import java.awt.event.ActionListener;

public class WelcomeUI extends javax.swing.JPanel {

    /**
     * Creates new form Login
     */
    public WelcomeUI() {
        initComponents();
    }

    public void addEventContinue(ActionListener event) {
        cmdContinue.addActionListener(event);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmdContiue = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        cmdContiue.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        cmdContiue.setForeground(new java.awt.Color(30, 122, 236));
        cmdContiue.setText("Continue");
        cmdContiue.setContentAreaFilled(false);
        cmdContiue.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cmdContiue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdContiueActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(cmdContiue, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(347, Short.MAX_VALUE)
                .addComponent(cmdContiue)
                .addGap(30, 30, 30))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cmdContiueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdContiueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmdContiueActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdContiue;
    // End of variables declaration//GEN-END:variables
